function getOrderResources() {
  return {
    status: 'success',
    message: '',
    payload: {
      selectPattern: {
        selectPattern1: [
          { selectPattern1: 'TR1', parts: 'jaket' },
          { selectPattern1: 'TR1P', parts: 'pants' },
          { selectPattern1: 'TR1V', parts: 'vest' },
        ],
        selectPattern2: [
          { selectPattern2: 'SY', selectPattern1: 'TR1' },
          { selectPattern2: 'A', selectPattern1: 'TR1' },
          { selectPattern2: 'AB', selectPattern1: 'TR1' },
          { selectPattern2: 'BE', selectPattern1: 'TR1' },
          { selectPattern2: 'JY', selectPattern1: 'TR1' },
          { selectPattern2: 'YA', selectPattern1: 'TR1' },
          { selectPattern2: 'SY', selectPattern1: 'TR1P' },
          { selectPattern2: 'A', selectPattern1: 'TR1P' },
          { selectPattern2: 'AB', selectPattern1: 'TR1P' },
          { selectPattern2: 'BE', selectPattern1: 'TR1P' },
          { selectPattern2: 'JY', selectPattern1: 'TR1P' },
          { selectPattern2: 'YA', selectPattern1: 'TR1P' },
          { selectPattern2: 'SY', selectPattern1: 'TR1V' },
          { selectPattern2: 'A', selectPattern1: 'TR1V' },
          { selectPattern2: 'AB', selectPattern1: 'TR1V' },
          { selectPattern2: 'BE', selectPattern1: 'TR1V' },
          { selectPattern2: 'JY', selectPattern1: 'TR1V' },
          { selectPattern2: 'YA', selectPattern1: 'TR1V' },
        ],
        selectPattern3: [
          { selectPattern3: 'SY3', selectPattern2: 'SY' },
          { selectPattern3: 'SY4', selectPattern2: 'SY' },
          { selectPattern3: 'SY5', selectPattern2: 'SY' },
          { selectPattern3: 'SY6', selectPattern2: 'SY' },
          { selectPattern3: 'SY7', selectPattern2: 'SY' },
          { selectPattern3: 'SY8', selectPattern2: 'SY' },
          { selectPattern3: 'SY9', selectPattern2: 'SY' },
          { selectPattern3: 'SY10', selectPattern2: 'SY' },
          { selectPattern3: 'SY11', selectPattern2: 'SY' },
          { selectPattern3: 'SY12', selectPattern2: 'SY' },
          { selectPattern3: 'SY13', selectPattern2: 'SY' },
          { selectPattern3: 'SY14', selectPattern2: 'SY' },
          { selectPattern3: 'SY15', selectPattern2: 'SY' },
          { selectPattern3: 'SY16', selectPattern2: 'SY' },
          { selectPattern3: 'SY17', selectPattern2: 'SY' },
          { selectPattern3: 'SY18', selectPattern2: 'SY' },
          { selectPattern3: 'A3', selectPattern2: 'A' },
          { selectPattern3: 'A4', selectPattern2: 'A' },
          { selectPattern3: 'A5', selectPattern2: 'A' },
          { selectPattern3: 'A6', selectPattern2: 'A' },
          { selectPattern3: 'A7', selectPattern2: 'A' },
          { selectPattern3: 'A8', selectPattern2: 'A' },
          { selectPattern3: 'AB3', selectPattern2: 'AB' },
          { selectPattern3: 'AB4', selectPattern2: 'AB' },
          { selectPattern3: 'AB5', selectPattern2: 'AB' },
          { selectPattern3: 'AB6', selectPattern2: 'AB' },
          { selectPattern3: 'AB7', selectPattern2: 'AB' },
          { selectPattern3: 'AB8', selectPattern2: 'AB' },
          { selectPattern3: 'BE3', selectPattern2: 'BE' },
          { selectPattern3: 'BE4', selectPattern2: 'BE' },
          { selectPattern3: 'BE5', selectPattern2: 'BE' },
          { selectPattern3: 'BE6', selectPattern2: 'BE' },
          { selectPattern3: 'BE7', selectPattern2: 'BE' },
          { selectPattern3: 'BE8', selectPattern2: 'BE' },
          { selectPattern3: 'JY3', selectPattern2: 'JY' },
          { selectPattern3: 'JY4', selectPattern2: 'JY' },
          { selectPattern3: 'JY5', selectPattern2: 'JY' },
          { selectPattern3: 'JY6', selectPattern2: 'JY' },
          { selectPattern3: 'JY7', selectPattern2: 'JY' },
          { selectPattern3: 'JY8', selectPattern2: 'JY' },
          { selectPattern3: 'YA3', selectPattern2: 'YA' },
          { selectPattern3: 'YA4', selectPattern2: 'YA' },
          { selectPattern3: 'YA5', selectPattern2: 'YA' },
          { selectPattern3: 'YA6', selectPattern2: 'YA' },
          { selectPattern3: 'YA7', selectPattern2: 'YA' },
          { selectPattern3: 'YA8', selectPattern2: 'YA' },
        ],
      },
    },
  };
}

function getFabricProductNos(productName: string, searchPattern: string) {
  const content = {
    status: 'success',
    message: '',
    payload: {
      productNos: [
        'X00001',
        'X00002',
        'X00003',
        'X00004',
        'X00005',
        'X00006',
        'X00007',
        'X00008',
        'X00009',
        'X00010',
      ],
    },
  };
  return content;
}
